# https://www.dicksmith.co.nz/dn/buy/kogan-smarterhome-smart-led-downlight-rgb-cool-warm-white-4-pack/
# These substitutions allow the end user to override certain values
substitutions:
  name: "kogan-rgbcct"
  friendly_name: "Kogan RGBCCT"
  
esphome:
  name: "${name}"
  platformio_options:
    board_build.f_flash: 40000000L
    board_build.flash_mode: dio
    board_build.flash_size: 4MB
  # Automatically add the mac address to the name
  # so you can use a single firmware for all devices
  name_add_mac_suffix: true

  # This will allow for (future) project identification,
  # configuration and updates.
  project:
    name: ned.kogan-rgbcct
    version: "1.32.0"

esp32:
  variant: ESP32C3
  board: esp32-c3-devkitm-1
  framework:
    type: esp-idf
    version: recommended

# To be able to get logs from the device via serial and api.
logger:

# API is a requirement of the dashboard import.
api:

# OTA is required for Over-the-Air updating
ota:

# This should point to the public location of this yaml file.
dashboard_import:
  package_import_url: github://neilvangeffen/ESPHome-KALEPDLRGBCCTA/project-template-kalepdlrgbccta.yaml@esp32

wifi:
  # Set up a wifi access point
  ap:
    password: "12345678"

# Sets up the improv via serial client for Wi-Fi provisioning
improv_serial:

binary_sensor:
  - platform: status
    name: "${friendly_name} Status"   # API Status of the device

text_sensor:
  - platform: version
    name: "${friendly_name} ESPHome Version"

sensor:
  - platform: wifi_signal
    name: "${friendly_name} WiFi Signal"
    update_interval: 60s

  - platform: uptime
    name: "${friendly_name} Uptime"
    
light:
  - platform: rgbct
    name: "${friendly_name}"
    red: output_red
    green: output_green
    blue: output_blue
    color_temperature: output_col_temp
    white_brightness: output_white_bright
    cold_white_color_temperature: 5000 K    #From Kogan Listing
    warm_white_color_temperature: 3000 K
    restore_mode: RESTORE_DEFAULT_ON 
    constant_brightness: true

# Example output entry
# ESP32-C3-12F Pins:
# - GPIO0        |  (TX) GPIO21 -
# - GPIO1        | (PWM) GPIO20 -
# - Reset        |       GPIO19 -
# - GPIO2 (PWM)  | (PWM) GPIO18 -
# - GPIO3 (PWM)  |        GPIO9 -
# - GPIO4        | (PWM) GPIO10 -
# - GPIO4        | (PWM)  GPIO8 -
# - 3V3          |          GND -
# | NC, | GPIO7 (PWM), | GPIO6 (PWM), | NC, | NC, | NC
#
# Kogan Pinout:
# P -> GPIO19
# C -> GPIO5
# G -> GPIO4
# R -> GPIO18 (PWM)
# B -> GPIO3  (PWM)
#
# Ned Pinout:
# P -> GPIO3  (PWM)
# C -> GPIO2  (PWM)
# G -> GPIO18 (PWM)
# R -> GPIO10 (PWM)
# B -> GPIO8  (PWM)
output:
  - platform: ledc
    id: output_red
    pin: GPIO10
  - platform: ledc
    id: output_green
    pin: GPIO18
  - platform: ledc
    id: output_blue
    pin: GPIO8
  - platform: ledc
    id: output_col_temp
    pin: GPIO2
  - platform: ledc
    id: output_white_bright
    pin: GPIO3